{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.828.0 (23.06)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Date\",\"Dataflows\",\"PyxisResponseStaging\",\"AlarisResponseStaging\",\"VOC Follow Up\",\"Customer Master\",\"ResponseDeletion\",\"PyxisNPSFactStaging\",\"KPI\",\"MinDate\",\"Today\",\"PyxisCustomers\",\"AlarisCustomer\",\"Customer\",\"Survey\",\"AlarisNPSFactStaging\",\"NPS Fact\",\"PyxisDimStaging\",\"AlarisDimStaging\",\"NPS Dim\",\"Pyxis Dim\",\"TrailingThreeYears\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "kpi.nps_variable_category": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "KPI",
                    "ConceptualProperty": "NPS (Variable Category)"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "NPS": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "kpi.response_variable_category": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "KPI",
                    "ConceptualProperty": "Response (Variable Category)"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Response Count": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "legendcategories.category": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "LegendCategories",
                    "ConceptualProperty": "Category"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "NPS Category:": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "pyxis_dim.department": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Pyxis Dim",
                    "ConceptualProperty": "Department"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Department": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Dataflows",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = PowerPlatform.Dataflows(null),",
          "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
          "    #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\" = Workspaces{[workspaceId=\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\"]}[Data]",
          "in",
          "    #\"4c4b04f0-f3fc-4be5-ad03-f3c5fbba8310\""
        ],
        "kind": "m",
        "lineageTag": "b30bdbf5-8a32-451c-9280-f92a73f7b8f0",
        "queryGroup": "Staging"
      },
      {
        "name": "ResponseDeletion",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "  Source = Table.FromRows(",
          "    Json.Document(",
          "      Binary.Decompress(",
          "        Binary.FromText(\"i45WCoo3dilJLQ1IzYoIz0/JMU1Rio0FAA==\", BinaryEncoding.Base64), ",
          "        Compression.Deflate",
          "      )",
          "    ), ",
          "    let",
          "      _t = ((type nullable text) meta [Serialized.Text = true])",
          "    in",
          "      type table [ResponseID = _t]",
          "  ), ",
          "  #\"Changed Type\" = Table.TransformColumnTypes(Source, {{\"ResponseID\", type text}})",
          "in",
          "  #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "c5a674b5-cd8d-4426-9d1c-10c1a50c9778",
        "queryGroup": "Staging"
      },
      {
        "name": "PyxisResponseStaging",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "  Source = Dataflows, ",
          "  #\"c68cfd67-9d70-4218-a0ea-02fd66e0d84f\" = Source",
          "    {[dataflowId = \"c68cfd67-9d70-4218-a0ea-02fd66e0d84f\"]}",
          "    [Data], ",
          "  RV_mms_canonical_bdx_qualtrics_nps_pyxis_ = #\"c68cfd67-9d70-4218-a0ea-02fd66e0d84f\"",
          "    {[entity = \"RV_mms_canonical_bdx_qualtrics_nps_pyxis\", version = \"\"]}",
          "    [Data], ",
          "  #\"Changed Type\" = Table.TransformColumnTypes(",
          "    RV_mms_canonical_bdx_qualtrics_nps_pyxis_, ",
          "    {{\"StartDate\", type datetime}, {\"EndDate\", type datetime}}",
          "  ), ",
          "  #\"Extracted Date\" = Table.TransformColumns(",
          "    #\"Changed Type\", ",
          "    {{\"StartDate\", DateTime.Date, type date}, {\"EndDate\", DateTime.Date, type date}}",
          "  ), ",
          "  #\"Filtered Rows\" = Table.SelectRows(#\"Extracted Date\", each ([DeletedFlag] <> \"1\")), ",
          "  #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"SurveyID\", each 1, Int64.Type), ",
          "  #\"Added Index\" = Table.AddIndexColumn(#\"Added Custom\", \"Index\", 1, 1, Int64.Type), ",
          "  #\"Renamed Columns1\" = Table.RenameColumns(#\"Added Index\", {{\"Index\", \"Response\"}}), ",
          "  AddedCustom = Table.AddColumn(",
          "    #\"Renamed Columns1\", ",
          "    \"ResponseUnique\", ",
          "    each [ResponseId] & Text.From([Response]), ",
          "    type text",
          "  ), ",
          "  #\"Filtered Rows1\" = Table.SelectRows(AddedCustom, each [EndDate] > TrailingThreeYears), ",
          "  #\"Replaced Value\" = Table.ReplaceValue(",
          "    #\"Filtered Rows1\", ",
          "    \"\", ",
          "    \"No Value\", ",
          "    Replacer.ReplaceValue, ",
          "    {\"Department\", \"Designation\"}",
          "  ), ",
          "  #\"Added Conditional Column\" = Table.AddColumn(",
          "    #\"Replaced Value\", ",
          "    \"HealthSight\", ",
          "    each if [HealthSightYN] = 1 then \"Yes\" else \"No\", ",
          "    type text",
          "  ), ",
          "  #\"Added Conditional Column C2Safe\" = Table.AddColumn(",
          "    #\"Added Conditional Column\", ",
          "    \"C2Safe\", ",
          "    each if [C2SafeYN] = 1 then \"Yes\" else \"No\", ",
          "    type text",
          "  )",
          "in",
          "  #\"Added Conditional Column C2Safe\""
        ],
        "kind": "m",
        "lineageTag": "a29ac96d-81f1-4778-8105-761d0445b3e3",
        "queryGroup": "Staging"
      },
      {
        "name": "AlarisResponseStaging",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "  Source = Dataflows, ",
          "  #\"f7fb921d-8fba-458d-aed8-9dc662fc4c3d\" = Source",
          "    {[dataflowId = \"f7fb921d-8fba-458d-aed8-9dc662fc4c3d\"]}",
          "    [Data], ",
          "  RV_mms_canonical_bdx_qualtrics_nps_alaris_ = #\"f7fb921d-8fba-458d-aed8-9dc662fc4c3d\"",
          "    {[entity = \"RV_mms_canonical_bdx_qualtrics_nps_alaris\", version = \"\"]}",
          "    [Data], ",
          "  #\"Changed Type\" = Table.TransformColumnTypes(",
          "    RV_mms_canonical_bdx_qualtrics_nps_alaris_, ",
          "    {{\"StartDate\", type datetime}, {\"EndDate\", type datetime}}",
          "  ), ",
          "  #\"Extracted Date\" = Table.TransformColumns(",
          "    #\"Changed Type\", ",
          "    {{\"StartDate\", DateTime.Date, type date}, {\"EndDate\", DateTime.Date, type date}}",
          "  ), ",
          "  #\"Filtered Rows\" = Table.SelectRows(#\"Extracted Date\", each ([DeletedFlag] <> \"1\")), ",
          "  #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"SurveyID\", each 2, Int64.Type), ",
          "  #\"Added Index\" = Table.AddIndexColumn(#\"Added Custom\", \"Index\", 1, 1, Int64.Type), ",
          "  #\"Renamed Columns1\" = Table.RenameColumns(#\"Added Index\", {{\"Index\", \"Response\"}}), ",
          "  AddedCustom = Table.AddColumn(",
          "    #\"Renamed Columns1\", ",
          "    \"ResponseUnique\", ",
          "    each [ResponseId] & Text.From([Response]), ",
          "    type text",
          "  ),",
          "    #\"Filtered Rows1\" = Table.SelectRows(AddedCustom, each [EndDate] > TrailingThreeYears)",
          "in",
          "    #\"Filtered Rows1\""
        ],
        "kind": "m",
        "lineageTag": "e752b72a-28d1-4373-aaff-40252050a911",
        "queryGroup": "Staging"
      },
      {
        "name": "MinDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": "#date(2016, 9, 1) meta [IsParameterQuery=true, List={#date(2016, 9, 1)}, DefaultValue=#date(2016, 9, 1), Type=\"Date\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d5d04411-e9ba-45b8-9394-0d662b9c06f3",
        "queryGroup": "Parameters"
      },
      {
        "name": "PyxisCustomers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = PyxisResponseStaging,",
          "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"ShipToNum\"}),",
          "    #\"Grouped Rows\" = Table.Group(#\"Removed Other Columns\", {\"ShipToNum\"}, {{\"Count\", each Table.RowCount(_), Int64.Type}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Grouped Rows\", each [ShipToNum] <> null and [ShipToNum] <> \"\")",
          "in",
          "    #\"Filtered Rows\""
        ],
        "kind": "m",
        "lineageTag": "f4f1c5a6-14be-4c05-af41-62f12447643c",
        "queryGroup": "Staging\\Transform"
      },
      {
        "name": "AlarisCustomer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = AlarisResponseStaging,",
          "    #\"Grouped Rows\" = Table.Group(Source, {\"ShipToNum\"}, {{\"Count\", each Table.RowCount(_), Int64.Type}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Grouped Rows\", each [ShipToNum] <> null and [ShipToNum] <> \"\")",
          "in",
          "    #\"Filtered Rows\""
        ],
        "kind": "m",
        "lineageTag": "1db20b6a-f29c-4222-a913-3f92fffbb31a",
        "queryGroup": "Staging\\Transform"
      },
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.Combine({PyxisCustomers, AlarisCustomer}),",
          "    #\"Grouped Rows\" = Table.Group(Source, {\"ShipToNum\"}, {{\"Count\", each List.Sum([Count]), type number}})",
          "in",
          "    #\"Grouped Rows\""
        ],
        "kind": "m",
        "lineageTag": "8131a892-9ff1-4314-a169-2009c2513844",
        "queryGroup": "Staging\\Transform"
      },
      {
        "name": "Today",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = DateTime.FixedLocalNow(),",
          "    #\"Extracted Date\" = Date.From(Source)",
          "in",
          "    #\"Extracted Date\""
        ],
        "kind": "m",
        "lineageTag": "53f8ba22-c10e-4c90-a80c-cd6e3716366d",
        "queryGroup": "Parameters"
      },
      {
        "name": "AlarisNPSFactStaging",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "  Source = AlarisResponseStaging, ",
          "  #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"EndDate\", \"ResponseId\", \"Q1NPSGroup\", \"Q1\", \"ShipToNum\", \"SurveyID\", \"Response\", \"ResponseUnique\"})",
          "in",
          "    #\"Removed Other Columns\""
        ],
        "kind": "m",
        "lineageTag": "e8015e5e-1499-44ba-8f02-8bb89d354d65",
        "queryGroup": "Staging\\Transform"
      },
      {
        "name": "PyxisNPSFactStaging",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "  Source = PyxisResponseStaging, ",
          "  #\"Reordered Columns\" = Table.ReorderColumns(",
          "    PyxisResponseStaging, ",
          "    {",
          "      \"StartDate\", ",
          "      \"EndDate\", ",
          "      \"Finished\", ",
          "      \"RecordedDate\", ",
          "      \"RecipientLastName\", ",
          "      \"RecipientFirstName\", ",
          "      \"RecipientEmail\", ",
          "      \"Q1NPSGroup\", ",
          "      \"Q1\", ",
          "      \"Q2\", ",
          "      \"Title\", ",
          "      \"SFDCAccountNo\", ",
          "      \"SFDCAccountName\", ",
          "      \"SFDCAccountCity\", ",
          "      \"SFDCAccountState\", ",
          "      \"SFDCPostalCode\", ",
          "      \"MasterIDNParent\", ",
          "      \"MasterIDNParentId\", ",
          "      \"IDNArea\", ",
          "      \"IDNTerritory\", ",
          "      \"IDNBucket\", ",
          "      \"IDNNumFacilities\", ",
          "      \"IDNNumStaffedBeds\", ",
          "      \"CustomerTenure\", ",
          "      \"CustomerType\", ",
          "      \"TerriLevel4Desc\", ",
          "      \"TerriLevel5Desc\", ",
          "      \"TerriLevel6Desc\", ",
          "      \"TerriLevel7Desc\", ",
          "      \"MedSalesCnslt\", ",
          "      \"CustomerSuccessManager\", ",
          "      \"NPSAccountOwner\", ",
          "      \"RegionalServiceDirector\", ",
          "      \"RegionalProfServDirector\", ",
          "      \"SFDCAccountCountry\", ",
          "      \"ESVersion\", ",
          "      \"SalesAVP\", ",
          "      \"RegionalSalesDirector\", ",
          "      \"CSMFlag\", ",
          "      \"SFDCAddress\", ",
          "      \"OtherProducts\", ",
          "      \"ShipToNum\", ",
          "      \"SurveySentDate\", ",
          "      \"CustomerTenureYrs\", ",
          "      \"CustomerTenureBin\", ",
          "      \"Department\", ",
          "      \"Designation\", ",
          "      \"ProductMix\", ",
          "      \"ProductMixMedStn\", ",
          "      \"ProductMixPAS\", ",
          "      \"AlarisYN\", ",
          "      \"C2SafeYN\", ",
          "      \"AnesthesiaYN\", ",
          "      \"HealthSightYN\", ",
          "      \"LogisticsYN\", ",
          "      \"IVPrepYN\", ",
          "      \"SupplyYN\", ",
          "      \"SFDCContactId\", ",
          "      \"DeletedFlag\", ",
          "      \"FollowUpAssigneeEmail\", ",
          "      \"FollowUpNeeded\", ",
          "      \"Q2ParentTopics\", ",
          "      \"Q2SentimentPolarity\", ",
          "      \"Q2SentimentScore\", ",
          "      \"Q2Sentiment\", ",
          "      \"Q2Topics\", ",
          "      \"Q2TopicSentimentLabel\", ",
          "      \"Q2TopicSentimentScore\", ",
          "      \"Sentiment\", ",
          "      \"ResponseId\"",
          "    }",
          "  ),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Reordered Columns\",{\"EndDate\", \"Q1NPSGroup\", \"Q1\", \"ShipToNum\", \"ResponseId\", \"SurveyID\", \"Response\", \"ResponseUnique\"})",
          "in",
          "    #\"Removed Other Columns\""
        ],
        "kind": "m",
        "lineageTag": "2e8cffcd-d000-438c-bba0-f07112d4e737",
        "queryGroup": "Staging\\Transform"
      },
      {
        "name": "PyxisDimStaging",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "  Source = PyxisResponseStaging, ",
          "  #\"Reordered Columns\" = Table.ReorderColumns(",
          "    PyxisResponseStaging, ",
          "    {",
          "      \"StartDate\", ",
          "      \"EndDate\", ",
          "      \"Finished\", ",
          "      \"RecordedDate\", ",
          "      \"RecipientLastName\", ",
          "      \"RecipientFirstName\", ",
          "      \"RecipientEmail\", ",
          "      \"Q1NPSGroup\", ",
          "      \"Q1\", ",
          "      \"Q2\", ",
          "      \"Title\", ",
          "      \"SFDCAccountNo\", ",
          "      \"SFDCAccountName\", ",
          "      \"SFDCAccountCity\", ",
          "      \"SFDCAccountState\", ",
          "      \"SFDCPostalCode\", ",
          "      \"MasterIDNParent\", ",
          "      \"MasterIDNParentId\", ",
          "      \"IDNArea\", ",
          "      \"IDNTerritory\", ",
          "      \"IDNBucket\", ",
          "      \"IDNNumFacilities\", ",
          "      \"IDNNumStaffedBeds\", ",
          "      \"CustomerTenure\", ",
          "      \"CustomerType\", ",
          "      \"TerriLevel4Desc\", ",
          "      \"TerriLevel5Desc\", ",
          "      \"TerriLevel6Desc\", ",
          "      \"TerriLevel7Desc\", ",
          "      \"MedSalesCnslt\", ",
          "      \"CustomerSuccessManager\", ",
          "      \"NPSAccountOwner\", ",
          "      \"RegionalServiceDirector\", ",
          "      \"RegionalProfServDirector\", ",
          "      \"SFDCAccountCountry\", ",
          "      \"ESVersion\", ",
          "      \"SalesAVP\", ",
          "      \"RegionalSalesDirector\", ",
          "      \"CSMFlag\", ",
          "      \"SFDCAddress\", ",
          "      \"OtherProducts\", ",
          "      \"ShipToNum\", ",
          "      \"SurveySentDate\", ",
          "      \"CustomerTenureYrs\", ",
          "      \"CustomerTenureBin\", ",
          "      \"Department\", ",
          "      \"Designation\", ",
          "      \"ProductMix\", ",
          "      \"ProductMixMedStn\", ",
          "      \"ProductMixPAS\", ",
          "      \"AlarisYN\", ",
          "      \"C2SafeYN\", ",
          "      \"AnesthesiaYN\", ",
          "      \"HealthSightYN\", ",
          "      \"LogisticsYN\", ",
          "      \"IVPrepYN\", ",
          "      \"SupplyYN\", ",
          "      \"SFDCContactId\", ",
          "      \"DeletedFlag\", ",
          "      \"FollowUpAssigneeEmail\", ",
          "      \"FollowUpNeeded\", ",
          "      \"Q2ParentTopics\", ",
          "      \"Q2SentimentPolarity\", ",
          "      \"Q2SentimentScore\", ",
          "      \"Q2Sentiment\", ",
          "      \"Q2Topics\", ",
          "      \"Q2TopicSentimentLabel\", ",
          "      \"Q2TopicSentimentScore\", ",
          "      \"Sentiment\", ",
          "      \"ResponseId\"",
          "    }",
          "  ),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Reordered Columns\",{\"EndDate\", \"SFDCAccountNo\", \"SFDCAccountName\", \"SFDCAccountCity\", \"SFDCAccountState\", \"CustomerType\", \"ShipToNum\", \"ResponseId\", \"SurveyID\", \"Response\", \"ResponseUnique\"})",
          "in",
          "    #\"Removed Other Columns\""
        ],
        "kind": "m",
        "lineageTag": "0cc869ad-998e-47a1-a1c5-aebd0993d291",
        "queryGroup": "Staging\\Transform"
      },
      {
        "name": "AlarisDimStaging",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "  Source = AlarisResponseStaging, ",
          "  #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"EndDate\", \"ResponseId\", \"SFDCAccountNo\", \"CustomerType\", \"SFDCAccountName\", \"SFDCAccountCity\", \"SFDCAccountState\", \"SFDCAccountCountry\", \"IDNArea\", \"IDNTerritory\", \"ShipToNum\", \"SurveyID\", \"Response\", \"ResponseUnique\"})",
          "in",
          "    #\"Removed Other Columns\""
        ],
        "kind": "m",
        "lineageTag": "d4c5a9c2-0a94-4db4-827c-e92719b468bf",
        "queryGroup": "Staging\\Transform"
      },
      {
        "name": "TrailingThreeYears",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let  ",
          "   CurrentDate = DateTime.Date(DateTime.LocalNow()),",
          "   StartDate = Date.AddYears(CurrentDate,-3)",
          "in   ",
          "   StartDate"
        ],
        "kind": "m",
        "lineageTag": "2d2ebc6b-faee-4999-a9ab-471a781d8c8c",
        "queryGroup": "Parameters"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Staging"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Model"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Model\\Dim"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Model\\Fact"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Staging\\Transform"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ],
        "folder": "Parameters"
      }
    ],
    "relationships": [
      {
        "name": "2be00076-7517-4b89-9eda-974b985e4d54",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "responseid",
        "fromTable": "VOC Follow Up",
        "toColumn": "ResponseId",
        "toTable": "NPS Fact"
      },
      {
        "name": "71198093-8fa1-447c-92f5-86682406ef47",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "ResponseId",
        "fromTable": "NPS Dim",
        "toColumn": "ResponseId",
        "toTable": "NPS Fact"
      },
      {
        "name": "30c5c49d-8708-4e4d-aead-fba6b2f8d730",
        "fromColumn": "SurveyID",
        "fromTable": "NPS Dim",
        "toColumn": "SurveyID",
        "toTable": "Survey"
      },
      {
        "name": "14f611f4-bafa-41bc-9e07-70d0a2b16075",
        "fromColumn": "EndDate",
        "fromTable": "NPS Fact",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "f6cdbefd-0672-4371-a17b-13ddeb94e937",
        "fromColumn": "ShipToNum",
        "fromTable": "NPS Fact",
        "toColumn": "CustomerIdNoLeadingZero",
        "toTable": "Customer Master"
      },
      {
        "name": "96c52333-1516-4ad8-ad3d-e0148442f2c7",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "ResponseId",
        "fromTable": "Pyxis Dim",
        "toColumn": "ResponseId",
        "toTable": "NPS Dim"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Customer Master",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerIdNoLeadingZero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "4a7f0b0d-cb0c-4a53-9c09-f419c1571200",
            "sourceColumn": "CustomerIdNoLeadingZero",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerSegment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "215339f1-827d-4201-8fcc-8234f3ac0047",
            "sourceColumn": "CustomerSegment",
            "summarizeBy": "none"
          },
          {
            "name": "Customer_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2a2786c-e7ef-4e7d-80c6-a3e4f49e514b",
            "sourceColumn": "Customer_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3558fe77-774e-4023-b478-d48e17d7d548",
            "sourceColumn": "Enterprise Account Name",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Network",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f34a8f64-b5cf-4d57-b96f-067077412093",
            "sourceColumn": "Enterprise Account Network",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Network Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c91ff08-2588-4977-9ad7-28b685968f79",
            "sourceColumn": "Enterprise Account Network Name",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Network Parent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c45a90a3-341a-47a4-891e-22306fa60517",
            "sourceColumn": "Enterprise Account Network Parent",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Network Parent Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7911a105-d9a0-4faf-8b7b-e98791339475",
            "sourceColumn": "Enterprise Account Network Parent Name",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfd9489c-f3cb-412a-95e9-eb6ac5f5b7c0",
            "sourceColumn": "Enterprise Account Number",
            "summarizeBy": "none"
          },
          {
            "name": "Enterprise Account Number SFID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ea23829-203a-40db-a24b-dd7ea6fb47f1",
            "sourceColumn": "Enterprise Account Number SFID",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "534aac6f-b0e9-472b-98c8-e99297e1a586",
            "sourceColumn": "State",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "46da24b8-0667-4f96-9dd9-05876df8bf1f",
        "partitions": [
          {
            "name": "Customer Master-fcde2358-abdc-411a-b45e-dd3e3e8f9cef",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = Dataflows,",
                "    #\"8bc11fbb-87d0-490d-ac7e-533062a85e3f\" = Source{[dataflowId=\"8bc11fbb-87d0-490d-ac7e-533062a85e3f\"]}[Data],",
                "    RV_mms_canonical_bdx_customer_master_ = #\"8bc11fbb-87d0-490d-ac7e-533062a85e3f\"{[entity=\"RV_mms_canonical_bdx_customer_master\",version=\"\"]}[Data],",
                "    #\"Merged Queries\" = Table.NestedJoin(RV_mms_canonical_bdx_customer_master_, {\"CustomerIdNoLeadingZero\"}, Customer, {\"ShipToNum\"}, \"Customer\", JoinKind.Inner),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(",
                "    #\"Merged Queries\" , ",
                "    {",
                "      {\"Name2\", type text}, ",
                "      {\"Street\", type text}, ",
                "      {\"City\", type text}, ",
                "      {\"County\", type text}, ",
                "      {\"ZipCode\", type text}, ",
                "      {\"State\", type text}, ",
                "      {\"Country\", type text}, ",
                "      {\"IndustryCode\", type text}, ",
                "      {\"Industry\", type text}, ",
                "      {\"AccountGroup\", type text}, ",
                "      {\"AccountGroupName\", type text}, ",
                "      {\"ClassificationCode\", type text}, ",
                "      {\"ClassificationDescription\", type text}, ",
                "      {\"AccountType\", type text}, ",
                "      {\"AccountTypeDescription\", type text}, ",
                "      {\"PhoneNumber\", type text}, ",
                "      {\"Longitude\", type text}, ",
                "      {\"Latitude\", type text}, ",
                "      {\"DeletionFlag\", type text}, ",
                "      {\"CustomerSWVersion_Infusion\", type text}, ",
                "      {\"InfusionTerritoryRepName\", type text}, ",
                "      {\"InfusionTerritoryName\", type text}, ",
                "      {\"InfusionTerritoryNumber\", type text}, ",
                "      {\"InfusionTerritoryRepEmployeeId\", type text}, ",
                "      {\"InfusionAreaRepName\", type text}, ",
                "      {\"InfusionAreaName\", type text}, ",
                "      {\"InfusionAreaNumber\", type text}, ",
                "      {\"InfusionAreaRepEmployeeId\", type text}, ",
                "      {\"InfusionRegionRepName\", type text}, ",
                "      {\"InfusionRegionName\", type text}, ",
                "      {\"InfusionRegionNumber\", type text}, ",
                "      {\"InfusionRegionRepEmployeeId\", type text}, ",
                "      {\"EnterpriseAccountNumberSFID\", type text}, ",
                "      {\"EnterpriseAccountNumber\", type text}, ",
                "      {\"EnterpriseAccountName\", type text}, ",
                "      {\"EnterpriseAccountNetwork\", type text}, ",
                "      {\"EnterpriseAccountNetworkName\", type text}, ",
                "      {\"EnterpriseAccountNetworkParent\", type text}, ",
                "      {\"EnterpriseAccountNetworkParentName\", type text}",
                "    }",
                "  ), ",
                "  #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([EnterpriseAccountNumber] <> \"\")), ",
                "  #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\",{\"Customer_ID\", \"CustomerIdNoLeadingZero\", \"State\", \"EnterpriseAccountNumberSFID\", \"EnterpriseAccountName\", \"EnterpriseAccountNetwork\", \"EnterpriseAccountNetworkName\", \"EnterpriseAccountNetworkParent\", \"EnterpriseAccountNetworkParentName\", \"EnterpriseAccountNumber\", \"CustomerSegment\"}), ",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    #\"Removed Other Columns\", ",
                "    {",
                "      {\"EnterpriseAccountNumberSFID\", \"Enterprise Account Number SFID\"}, ",
                "      {\"EnterpriseAccountNumber\", \"Enterprise Account Number\"}, ",
                "      {\"EnterpriseAccountName\", \"Enterprise Account Name\"}, ",
                "      {\"EnterpriseAccountNetwork\", \"Enterprise Account Network\"}, ",
                "      {\"EnterpriseAccountNetworkName\", \"Enterprise Account Network Name\"}, ",
                "      {\"EnterpriseAccountNetworkParent\", \"Enterprise Account Network Parent\"}, ",
                "      {\"EnterpriseAccountNetworkParentName\", \"Enterprise Account Network Parent Name\"}",
                "    }",
                "  )",
                "in",
                "  #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "eefce39a-21ae-4017-8a80-8bf344d74c02",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "FM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f991a348-f733-46f9-9089-6d62310502e4",
            "sourceColumn": "FM",
            "summarizeBy": "none"
          },
          {
            "name": "FM_sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9ae0bbdc-c8ae-417b-ab9e-fdc6ff0b7fdc",
            "sourceColumn": "FM_sort",
            "summarizeBy": "none"
          },
          {
            "name": "FQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "79e3e31d-278f-4620-a9f8-fc0ad6ffd538",
            "sortByColumn": "fiscal_quarter_num",
            "sourceColumn": "FQ",
            "summarizeBy": "none"
          },
          {
            "name": "FY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0727e7b3-2ba5-43d8-b362-ebe3f4135bdc",
            "sourceColumn": "FY",
            "summarizeBy": "none"
          },
          {
            "name": "FY YY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ccd7d88e-9d55-453e-8680-a193022a43fc",
            "sourceColumn": "FY YY",
            "summarizeBy": "none"
          },
          {
            "name": "FYQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6d927f6-6856-4f1e-a84b-cee760240941",
            "sourceColumn": "FYQ",
            "summarizeBy": "none"
          },
          {
            "name": "FYYY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89192bec-7a26-46ea-9905-ce0beb235a5d",
            "sourceColumn": "FYYY",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "460c3032-41c5-4606-94d5-b076b624627e",
            "sortByColumn": "fiscal_month_num",
            "sourceColumn": "Fiscal Month",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d96bb7e6-9b7b-4691-a906-485a5e5f799a",
            "sourceColumn": "Fiscal Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "calendar_date_weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a235a7df-3e0f-4d57-ae73-7225e25e36ab",
            "sourceColumn": "calendar_date_weekday",
            "summarizeBy": "none"
          },
          {
            "name": "calendaryear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7a4bca88-f699-4f13-a055-fc11483733e4",
            "sourceColumn": "calendaryear",
            "summarizeBy": "none"
          },
          {
            "name": "date_yyyymm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "643a7482-6093-4c7a-9d35-aa59727ed9b2",
            "sourceColumn": "date_yyyymm",
            "summarizeBy": "none"
          },
          {
            "name": "date_yyyymmdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b04f109f-5fad-4af0-98f9-8d9b8b194658",
            "sourceColumn": "date_yyyymmdd",
            "summarizeBy": "none"
          },
          {
            "name": "day_of_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68c13928-f077-4fdc-b87e-b1e0407f3a8c",
            "sourceColumn": "day_of_year",
            "summarizeBy": "none"
          },
          {
            "name": "first_date_of_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d3b24e06-775d-4ea2-bf60-7e3876258790",
            "sourceColumn": "first_date_of_month",
            "summarizeBy": "none"
          },
          {
            "name": "fiscal_month_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fb69e71b-3788-432b-9060-d3e61976e871",
            "sourceColumn": "fiscal_month_num",
            "summarizeBy": "none"
          },
          {
            "name": "fiscal_quarter_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0ab52d4f-8772-419b-9ac5-7a22dd0499e6",
            "sourceColumn": "fiscal_quarter_num",
            "summarizeBy": "none"
          },
          {
            "name": "fiscal_year_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a23a72df-1b82-4abc-8350-42c6a3146f5f",
            "sourceColumn": "fiscal_year_month",
            "summarizeBy": "none"
          },
          {
            "name": "fiscal_year_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "796d3d0b-7515-4a70-a795-06926a2467b1",
            "sourceColumn": "fiscal_year_name",
            "summarizeBy": "none"
          },
          {
            "name": "fiscal_year_quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5677123-140d-45f3-a2d6-0d2a62c9420f",
            "sourceColumn": "fiscal_year_quarter",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "FY Hierarchy",
            "levels": [
              {
                "name": "FY YY",
                "column": "FY YY",
                "lineageTag": "a7db1c66-5681-4bc1-8a29-d2ac02580794",
                "ordinal": 0
              },
              {
                "name": "FQ",
                "column": "FQ",
                "lineageTag": "2e116b5d-546b-49a1-a34b-eb6a8a9c4f9e",
                "ordinal": 1
              },
              {
                "name": "Fiscal Month",
                "column": "Fiscal Month",
                "lineageTag": "eee6d46d-e95a-4efe-8e78-c4c7df395afa",
                "ordinal": 2
              }
            ],
            "lineageTag": "2fcd6a9f-1c0f-4de6-a912-477da85c115f"
          }
        ],
        "lineageTag": "db6db2fa-85f0-42ad-93f7-61416478b538",
        "partitions": [
          {
            "name": "Date-7af14442-be7a-4148-b055-3311309fa9c0",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "  Source = PowerBI.Dataflows(null), ",
                "  #\"8002b6b6-3a67-4bb0-82f9-e38851e04e8f\" = Source",
                "    {[workspaceId = \"8002b6b6-3a67-4bb0-82f9-e38851e04e8f\"]}",
                "    [Data], ",
                "  #\"26ec83ee-cd97-49d6-8186-553e7629d769\" = #\"8002b6b6-3a67-4bb0-82f9-e38851e04e8f\"",
                "    {[dataflowId = \"26ec83ee-cd97-49d6-8186-553e7629d769\"]}",
                "    [Data], ",
                "  RV_canonical_calendar = #\"26ec83ee-cd97-49d6-8186-553e7629d769\"",
                "    {[entity = \"RV_canonical_calendar\"]}",
                "    [Data], ",
                "  ModelDates = Table.SelectRows(",
                "    RV_canonical_calendar, ",
                "    each [calendar_date] >= TrailingThreeYears and [calendar_date] <= Today",
                "  ), ",
                "  #\"Added Custom\" = Table.AddColumn(ModelDates, \"FM\", each [calendar_month]), ",
                "  #\"Renamed Columns\" = Table.RenameColumns(",
                "    #\"Added Custom\", ",
                "    {{\"fiscal_year\", \"FY YY\"}, {\"fiscal_quarter\", \"Fiscal Quarter\"}, {\"FM\", \"Fiscal Month\"}}",
                "  ), ",
                "  #\"Renamed Columns1\" = Table.RenameColumns(",
                "    #\"Renamed Columns\", ",
                "    {{\"fyyyy_month_name\", \"FM\"}, {\"fy_quarter\", \"FQ\"}}",
                "  ), ",
                "  #\"Added Custom1\" = Table.AddColumn(#\"Renamed Columns1\", \"Custom\", each [FY YY]), ",
                "  #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Custom1\", {{\"Custom\", \"FY\"}}), ",
                "  #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns2\", {{\"FY\", type text}}), ",
                "  #\"Added Custom2\" = Table.AddColumn(#\"Changed Type\", \"FYYY\", each \"FY\" & Text.End([FY], 2)), ",
                "  #\"Renamed Columns3\" = Table.RenameColumns(#\"Added Custom2\", {{\"fyyyy_quarter\", \"FYQ\"}}), ",
                "  #\"Added Custom3\" = Table.AddColumn(#\"Renamed Columns3\", \"FM_sort\", each [calendar_date]), ",
                "  #\"Calculated Start of Month\" = Table.TransformColumns(",
                "    #\"Added Custom3\", ",
                "    {{\"FM_sort\", Date.StartOfMonth, type date}}",
                "  ), ",
                "  #\"Changed Type1\" = Table.TransformColumnTypes(",
                "    #\"Calculated Start of Month\", ",
                "    {{\"FM_sort\", Int64.Type}}",
                "  ), ",
                "  #\"Removed Other Columns\" = Table.SelectColumns(",
                "    #\"Changed Type1\", ",
                "    {",
                "      \"calendar_date\", ",
                "      \"calendar_date_weekday\", ",
                "      \"calendaryear\", ",
                "      \"date_yyyymm\", ",
                "      \"date_yyyymmdd\", ",
                "      \"day_of_year\", ",
                "      \"first_date_of_month\", ",
                "      \"Fiscal Month\", ",
                "      \"Fiscal Quarter\", ",
                "      \"fiscal_month_num\", ",
                "      \"fiscal_quarter_num\", ",
                "      \"fiscal_year_month\", ",
                "      \"fiscal_year_name\", ",
                "      \"fiscal_year_quarter\", ",
                "      \"FM\", ",
                "      \"FM_sort\", ",
                "      \"FQ\", ",
                "      \"FY\", ",
                "      \"FY YY\", ",
                "      \"FYQ\", ",
                "      \"FYYY\"",
                "    }",
                "  ),",
                "    #\"Renamed Columns4\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"calendar_date\", \"Date\"}})",
                "in",
                "  #\"Renamed Columns4\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "eb25516b-633d-449c-833b-b109006445d4",
            "sourceColumn": "KPI",
            "summarizeBy": "none"
          },
          {
            "name": "KPI Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d35c158d-4187-44e5-af05-d58f341b4558",
            "sourceColumn": "KPI Value",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "caa9d731-2bdd-4276-a7d6-8b13e80a3f69",
        "measures": [
          {
            "name": "Responses",
            "displayFolder": "Base Measures",
            "expression": "DISTINCTCOUNT('NPS Fact'[ResponseId])",
            "formatString": "0",
            "lineageTag": "802faef3-5e28-4d47-adca-686f8948873c"
          },
          {
            "name": "Detractor",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": [
              "",
              "DIVIDE(",
              "\tCALCULATE(",
              "\tCOUNT('NPS Fact'[ResponseId]),",
              "\t'NPS Fact'[Q1NPSGroup] IN { \"Detractor\" }",
              "),",
              "\tCOUNT('NPS Fact'[ResponseId])",
              ")"
            ],
            "lineageTag": "fcccc380-80cc-4f44-9027-52927b69ad3a"
          },
          {
            "name": "Promoters",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Base Measures",
            "expression": [
              "",
              "DIVIDE(",
              "CALCULATE(",
              "\tCOUNT('NPS Fact'[ResponseId]),",
              "\t'NPS Fact'[Q1NPSGroup] IN { \"Promoter\" }",
              "),",
              "\tCOUNT('NPS Fact'[ResponseId])",
              ")"
            ],
            "lineageTag": "3e214ce1-a558-44ff-b78a-d9974a45859c"
          },
          {
            "name": "NPS",
            "expression": [
              "",
              "IF (",
              "    ISBLANK ( [Promoters] * 100 - [Detractor] * 100 ), ",
              "    BLANK(),",
              "     ( [Promoters] * 100 - [Detractor] * 100 )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "2a188bc2-bf9c-40a9-8449-7b5d3ab6e8b8"
          }
        ],
        "partitions": [
          {
            "name": "KPI-dbe5f112-28d1-41f8-9b09-296f8483be1d",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "  Source = Table.FromRows(",
                "    Json.Document(",
                "      Binary.Decompress(",
                "        Binary.FromText(",
                "          \"i45WCqisyCxW8AsIVnDPT8xR0lEyMVWK1YlW8s3MA4kCBXQNDQwgQokVUCG4SGYKVATCd8xJLMpENswIKB4LAA==\",",
                "          BinaryEncoding.Base64",
                "        ),",
                "        Compression.Deflate",
                "      )",
                "    ),",
                "    let",
                "      _t = ((type nullable text) meta [Serialized.Text = true])",
                "    in",
                "      type table [KPI = _t, #\"KPI Value\" = _t]",
                "  ),",
                "  #\"Changed Type\" = Table.TransformColumnTypes(",
                "    Source,",
                "    {{\"KPI\", type text}, {\"KPI Value\", Int64.Type}}",
                "  )",
                "in",
                "  #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "NPS Dim",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24ad0c77-403e-4116-9624-79e17e294ac9",
            "sourceColumn": "CustomerType",
            "summarizeBy": "none"
          },
          {
            "name": "EndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "bbf9b088-e40d-4db2-81e6-04f2e1702892",
            "sourceColumn": "EndDate",
            "summarizeBy": "none"
          },
          {
            "name": "IDNArea",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8577811b-c198-4723-a857-c51496c8bdf0",
            "sourceColumn": "IDNArea",
            "summarizeBy": "none"
          },
          {
            "name": "IDNTerritory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2635a055-45ec-4f4a-b3cc-33b86d0d15cb",
            "sourceColumn": "IDNTerritory",
            "summarizeBy": "none"
          },
          {
            "name": "Response",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "764af78d-cb70-485f-9eed-410fe5505529",
            "sourceColumn": "Response",
            "summarizeBy": "sum"
          },
          {
            "name": "ResponseId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "7f934d74-1909-412b-96f3-e16ea44ccff1",
            "sourceColumn": "ResponseId",
            "summarizeBy": "none"
          },
          {
            "name": "ResponseUnique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe009758-40cb-44a1-8fc2-cb6ba7e69790",
            "sourceColumn": "ResponseUnique",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCAccountCity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "826ab393-b0cf-4887-9b67-05b40da6b54b",
            "sourceColumn": "SFDCAccountCity",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCAccountCountry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c9baab0-3dc7-4eef-89ea-9c594b8a11b1",
            "sourceColumn": "SFDCAccountCountry",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCAccountName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1254b3e-a859-4f97-b5af-6fdffce709d3",
            "sourceColumn": "SFDCAccountName",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCAccountNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62b0e5cf-9a3f-4f6d-9cac-2b62b7b0741b",
            "sourceColumn": "SFDCAccountNo",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCAccountState",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "accd2c7a-68ca-47e7-90cb-a71b7616d0e0",
            "sourceColumn": "SFDCAccountState",
            "summarizeBy": "none"
          },
          {
            "name": "ShipToNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09ad0041-a4fb-445c-a51c-3f0962264434",
            "sourceColumn": "ShipToNum",
            "summarizeBy": "none"
          },
          {
            "name": "SurveyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "866d2cd0-00f0-4710-85b1-31ec2ebf154b",
            "sourceColumn": "SurveyID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4fa75d73-13ed-41e8-b017-262594947edd",
        "partitions": [
          {
            "name": "NPS Dim-6b0bb77c-0d1e-4119-ad2c-61c92d62816f",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = Table.Combine({PyxisDimStaging, AlarisDimStaging})",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "NPS Fact",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "EndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d4513cbc-92f9-49f6-9667-fbff03a31323",
            "sourceColumn": "EndDate",
            "summarizeBy": "none"
          },
          {
            "name": "Q1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "daf568fd-fc7f-4082-bb31-fcffafe9b7b7",
            "sourceColumn": "Q1",
            "summarizeBy": "sum"
          },
          {
            "name": "Q1NPSGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5b9f52f-3494-4215-ad9b-da4c292045a3",
            "sourceColumn": "Q1NPSGroup",
            "summarizeBy": "none"
          },
          {
            "name": "Response",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c465fa4-98cd-4c87-9426-75d58a9b4d46",
            "sourceColumn": "Response",
            "summarizeBy": "sum"
          },
          {
            "name": "ResponseId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "4133199c-6d76-485e-aae1-5916139e7afd",
            "sourceColumn": "ResponseId",
            "summarizeBy": "none"
          },
          {
            "name": "ResponseUnique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fba55bd7-1072-4a77-8d6a-10cd3e460a49",
            "sourceColumn": "ResponseUnique",
            "summarizeBy": "none"
          },
          {
            "name": "ShipToNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e063c11-334c-47f6-9e90-2db0e36577a7",
            "sourceColumn": "ShipToNum",
            "summarizeBy": "none"
          },
          {
            "name": "SurveyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ae4a9fd9-deec-4e41-a07f-2ea7cfe81e66",
            "sourceColumn": "SurveyID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "3a4d64e6-8f6f-4506-837e-ba75e92e6d39",
        "partitions": [
          {
            "name": "NPS Fact-f36a1e83-2a85-4caa-bc06-b0c4336d98ee",
            "mode": "import",
            "queryGroup": "Model\\Fact",
            "source": {
              "expression": [
                "let",
                "    Source = Table.Combine({PyxisNPSFactStaging, AlarisNPSFactStaging})",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Pyxis Dim",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "AlarisYN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "171d6cbe-0155-4109-a601-3fb8cb6a641b",
            "sourceColumn": "AlarisYN",
            "summarizeBy": "sum"
          },
          {
            "name": "AnesthesiaYN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0825160-2b59-4733-bb0f-e27e0e45650b",
            "sourceColumn": "AnesthesiaYN",
            "summarizeBy": "sum"
          },
          {
            "name": "C2Safe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2703ef29-14e9-4649-9864-759ea2c6ba2a",
            "sourceColumn": "C2Safe",
            "summarizeBy": "none"
          },
          {
            "name": "C2SafeYN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "78451fdd-b004-4a88-a529-fa417b7a6cb9",
            "sourceColumn": "C2SafeYN",
            "summarizeBy": "sum"
          },
          {
            "name": "CSMFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a55f739-4527-465a-af51-1b59d0e6bcd9",
            "sourceColumn": "CSMFlag",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerSuccessManager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9011a801-bc25-4051-a488-6fc42b9a6a4f",
            "sourceColumn": "CustomerSuccessManager",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerTenure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "206fb5f5-0f44-4465-bdbc-503759059355",
            "sourceColumn": "CustomerTenure",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerTenureBin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2ce9dda-91c6-4f5a-b8d7-98cfeb5512d6",
            "sourceColumn": "CustomerTenureBin",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerTenureYrs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eacd4d31-ff66-4b6d-8058-78af4730ef55",
            "sourceColumn": "CustomerTenureYrs",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e2fb563-3bf4-4a2e-b0ce-bc5667ae1783",
            "sourceColumn": "CustomerType",
            "summarizeBy": "none"
          },
          {
            "name": "DeletedFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ae61e8b-8f43-4ce2-85b9-412355e9d2d5",
            "sourceColumn": "DeletedFlag",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d51a652a-5463-4459-b5c6-459f3acdcc6e",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Designation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03d353d5-899a-445e-878c-f0787e96c067",
            "sourceColumn": "Designation",
            "summarizeBy": "none"
          },
          {
            "name": "ESVersion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Pyxis Dim\",\"TableItemName\":\"ESVersion (groups)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "95005367-45b6-453d-8391-234b82bd8c58",
            "sourceColumn": "ESVersion",
            "summarizeBy": "none"
          },
          {
            "name": "ESVersion (groups)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"p\",\"Entity\":\"Pyxis Dim\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"ESVersion\"}}],\"GroupItems\":[{\"DisplayName\":\"(Blank)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"1.3\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"ESVersion\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'1.3.2'\"}}],[{\"Literal\":{\"Value\":\"'1.3.4'\"}}]]}}},{\"DisplayName\":\"1.4\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"ESVersion\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'1.4.2'\"}}],[{\"Literal\":{\"Value\":\"'1.4.4'\"}}],[{\"Literal\":{\"Value\":\"'1.4.4.1'\"}}],[{\"Literal\":{\"Value\":\"'1.4.4.2'\"}}]]}}},{\"DisplayName\":\"1.5\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"ESVersion\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'1.5.2.1'\"}}],[{\"Literal\":{\"Value\":\"'1.5.2.2'\"}}]]}}},{\"DisplayName\":\"1.6\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"ESVersion\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'1.6.1'\"}}]]}}},{\"DisplayName\":\"1.7\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"ESVersion\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'1.7.2'\"}}]]}}},{\"DisplayName\":\"Other\"}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('Pyxis Dim'[ESVersion]),",
              "\t\"(Blank)\",",
              "\t'Pyxis Dim'[ESVersion] IN {\"1.3.2\",",
              "\t\t\"1.3.4\"},",
              "\t\"1.3\",",
              "\t'Pyxis Dim'[ESVersion] IN {\"1.4.2\",",
              "\t\t\"1.4.4\",",
              "\t\t\"1.4.4.1\",",
              "\t\t\"1.4.4.2\"},",
              "\t\"1.4\",",
              "\t'Pyxis Dim'[ESVersion] IN {\"1.5.2.1\",",
              "\t\t\"1.5.2.2\"},",
              "\t\"1.5\",",
              "\t'Pyxis Dim'[ESVersion] IN {\"1.6.1\"},",
              "\t\"1.6\",",
              "\t'Pyxis Dim'[ESVersion] IN {\"1.7.2\"},",
              "\t\"1.7\",",
              "\t\"Other\"",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Pyxis Dim"
                          }
                        },
                        "Property": "ESVersion"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3335ccfc-75a2-4265-a921-5d9797dae373",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "EndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "20b924d8-2ee6-43da-9f86-bc2267b6d776",
            "sourceColumn": "EndDate",
            "summarizeBy": "none"
          },
          {
            "name": "Finished",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e04c3625-f218-438f-80ea-db3acaa2d8c8",
            "sourceColumn": "Finished",
            "summarizeBy": "none"
          },
          {
            "name": "FollowUpAssigneeEmail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "524fc1da-d859-4e47-8253-c713fcdc8603",
            "sourceColumn": "FollowUpAssigneeEmail",
            "summarizeBy": "none"
          },
          {
            "name": "FollowUpNeeded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70594bfe-e791-423a-a27f-e6270e1e5698",
            "sourceColumn": "FollowUpNeeded",
            "summarizeBy": "none"
          },
          {
            "name": "HealthSight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5366d0e8-89d6-4fa6-bb3f-6bb9e5e253fc",
            "sourceColumn": "HealthSight",
            "summarizeBy": "none"
          },
          {
            "name": "HealthSightYN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c955b2b-fbff-4f38-8d99-65f6030deb21",
            "sourceColumn": "HealthSightYN",
            "summarizeBy": "sum"
          },
          {
            "name": "IDNArea",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f187692c-9c09-42e4-928e-9fc408a48574",
            "sourceColumn": "IDNArea",
            "summarizeBy": "none"
          },
          {
            "name": "IDNBucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ebc45c0-f86e-4744-a6fd-fb9d8f0f9a1f",
            "sourceColumn": "IDNBucket",
            "summarizeBy": "none"
          },
          {
            "name": "IDNNumFacilities",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d8e05d4-141a-4bb5-b3c8-0b7b6ecfd8b4",
            "sourceColumn": "IDNNumFacilities",
            "summarizeBy": "sum"
          },
          {
            "name": "IDNNumStaffedBeds",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "00e559e9-a91a-4beb-8596-2b0c34beaaf3",
            "sourceColumn": "IDNNumStaffedBeds",
            "summarizeBy": "sum"
          },
          {
            "name": "IDNTerritory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84b38c61-43ce-4248-b9d6-434bfd4740dc",
            "sourceColumn": "IDNTerritory",
            "summarizeBy": "none"
          },
          {
            "name": "IVPrepYN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "353d2024-348f-49e2-94c2-40a4076de71a",
            "sourceColumn": "IVPrepYN",
            "summarizeBy": "sum"
          },
          {
            "name": "LogisticsYN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "619c5af2-67a3-4d7c-ac59-0863e6fbcea5",
            "sourceColumn": "LogisticsYN",
            "summarizeBy": "sum"
          },
          {
            "name": "MasterIDNParent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8e8b0a1-c231-4bab-b8ff-ae0f457d76f3",
            "sourceColumn": "MasterIDNParent",
            "summarizeBy": "none"
          },
          {
            "name": "MasterIDNParentId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f74b911b-1b02-41dc-84b4-d7189c7144cc",
            "sourceColumn": "MasterIDNParentId",
            "summarizeBy": "none"
          },
          {
            "name": "MedSalesCnslt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0d366fb-aabd-436e-82c5-eb8bd666729b",
            "sourceColumn": "MedSalesCnslt",
            "summarizeBy": "none"
          },
          {
            "name": "NPSAccountOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04acd643-c211-4e7f-9f76-7a23ef90647e",
            "sourceColumn": "NPSAccountOwner",
            "summarizeBy": "none"
          },
          {
            "name": "OtherProducts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f2946b6-037c-445a-a898-28dacd2f7125",
            "sourceColumn": "OtherProducts",
            "summarizeBy": "none"
          },
          {
            "name": "ProductMix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10bf6433-4e0f-4942-93c4-c93cb7a380ae",
            "sourceColumn": "ProductMix",
            "summarizeBy": "none"
          },
          {
            "name": "ProductMixMedStn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60e7f4ee-ae37-4214-b80f-a4c738cfd579",
            "sourceColumn": "ProductMixMedStn",
            "summarizeBy": "none"
          },
          {
            "name": "ProductMixPAS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9c53344-f4ce-468e-9d30-9b734570b2ed",
            "sourceColumn": "ProductMixPAS",
            "summarizeBy": "none"
          },
          {
            "name": "Q1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "19d994e7-e6e5-4290-a732-e6a618a3d899",
            "sourceColumn": "Q1",
            "summarizeBy": "sum"
          },
          {
            "name": "Q1NPSGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fe3b42f-bc02-4f58-9286-8648d33f4a5f",
            "sourceColumn": "Q1NPSGroup",
            "summarizeBy": "none"
          },
          {
            "name": "Q2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd73bd6c-cceb-465a-8a9e-8181ba449fe3",
            "sourceColumn": "Q2",
            "summarizeBy": "none"
          },
          {
            "name": "Q2ParentTopics",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2ce3a1f-5b43-4abc-9a25-1ae78e817b54",
            "sourceColumn": "Q2ParentTopics",
            "summarizeBy": "none"
          },
          {
            "name": "Q2Sentiment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a45c7b41-ccbc-4165-a786-8ea63fee23fa",
            "sourceColumn": "Q2Sentiment",
            "summarizeBy": "none"
          },
          {
            "name": "Q2SentimentPolarity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e606cf4-08c5-4c8f-95cf-1afaf3785435",
            "sourceColumn": "Q2SentimentPolarity",
            "summarizeBy": "none"
          },
          {
            "name": "Q2SentimentScore",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcc9745b-450c-41a7-aad3-26030106401c",
            "sourceColumn": "Q2SentimentScore",
            "summarizeBy": "none"
          },
          {
            "name": "Q2TopicSentimentLabel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85d20403-b641-4f2c-96e5-8253ca5d24b8",
            "sourceColumn": "Q2TopicSentimentLabel",
            "summarizeBy": "none"
          },
          {
            "name": "Q2TopicSentimentScore",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85a2cd63-bc59-4819-9f55-665ea8b0014b",
            "sourceColumn": "Q2TopicSentimentScore",
            "summarizeBy": "none"
          },
          {
            "name": "Q2Topics",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e1108ed-fa83-4be0-a6ab-8ff9ce1b5a82",
            "sourceColumn": "Q2Topics",
            "summarizeBy": "none"
          },
          {
            "name": "RecipientEmail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "837226d9-793d-493e-94f9-a2c551bf442f",
            "sourceColumn": "RecipientEmail",
            "summarizeBy": "none"
          },
          {
            "name": "RecipientFirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ee2b1db-ffa2-4f9b-a7cf-dfccf3f4e9ee",
            "sourceColumn": "RecipientFirstName",
            "summarizeBy": "none"
          },
          {
            "name": "RecipientLastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce2bf649-9026-4f48-9dcf-403087c7b343",
            "sourceColumn": "RecipientLastName",
            "summarizeBy": "none"
          },
          {
            "name": "RecordedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c3b2f83-363c-4025-a5a7-aa064571aaf4",
            "sourceColumn": "RecordedDate",
            "summarizeBy": "none"
          },
          {
            "name": "RegionalProfServDirector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4ed20b9-b892-4ee7-8a63-a97129fdf0a4",
            "sourceColumn": "RegionalProfServDirector",
            "summarizeBy": "none"
          },
          {
            "name": "RegionalSalesDirector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3e500de-4b3a-4011-9c06-57fa2dcbad1e",
            "sourceColumn": "RegionalSalesDirector",
            "summarizeBy": "none"
          },
          {
            "name": "RegionalServiceDirector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "226540e5-a375-40ed-bfaf-b5567abd5a2d",
            "sourceColumn": "RegionalServiceDirector",
            "summarizeBy": "none"
          },
          {
            "name": "Response",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ef699bdb-7857-41bb-a19d-2e8ca8f351a5",
            "sourceColumn": "Response",
            "summarizeBy": "sum"
          },
          {
            "name": "ResponseId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "2d9b297d-a21a-4580-a088-b56a318fece3",
            "sourceColumn": "ResponseId",
            "summarizeBy": "none"
          },
          {
            "name": "ResponseUnique",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7eb9556f-ba5f-4f1b-9444-0b95a58101a2",
            "sourceColumn": "ResponseUnique",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCAccountCity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b08c970e-4bda-405a-8d0d-3a4f631eb344",
            "sourceColumn": "SFDCAccountCity",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCAccountCountry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db20a13a-e7df-4622-a319-efaba4b2866e",
            "sourceColumn": "SFDCAccountCountry",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCAccountName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "713e7edb-18a1-4545-b14a-e795bfc5be9e",
            "sourceColumn": "SFDCAccountName",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCAccountNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61441a97-b3d2-4cac-83b5-1a8333566d02",
            "sourceColumn": "SFDCAccountNo",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCAccountState",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52ac8c9f-8c2d-4b4e-a72b-0e02e26cfe0b",
            "sourceColumn": "SFDCAccountState",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e9680d4-b35a-484f-9e38-ed7717bc31bd",
            "sourceColumn": "SFDCAddress",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCContactId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5132c4e-e666-4920-9316-599831a320ea",
            "sourceColumn": "SFDCContactId",
            "summarizeBy": "none"
          },
          {
            "name": "SFDCPostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18d302c2-34fd-4adc-b59b-a27e43c942b7",
            "sourceColumn": "SFDCPostalCode",
            "summarizeBy": "none"
          },
          {
            "name": "SalesAVP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12530176-3065-40ac-a80e-dd7dfccaef09",
            "sourceColumn": "SalesAVP",
            "summarizeBy": "none"
          },
          {
            "name": "Sentiment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "effdabbf-c1ea-40df-9fd7-70d0de97c683",
            "sourceColumn": "Sentiment",
            "summarizeBy": "none"
          },
          {
            "name": "ShipToNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fc4d10c-8c81-49f9-a3be-6596749e1f8d",
            "sourceColumn": "ShipToNum",
            "summarizeBy": "none"
          },
          {
            "name": "StartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "036dc26e-ac5f-4124-a86d-37211517588a",
            "sourceColumn": "StartDate",
            "summarizeBy": "none"
          },
          {
            "name": "SupplyYN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8dab3b2-2dfe-468e-8783-c8c905c72a0c",
            "sourceColumn": "SupplyYN",
            "summarizeBy": "sum"
          },
          {
            "name": "SurveyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c1cbd3e4-a920-44d0-ae4f-2118699c14dd",
            "sourceColumn": "SurveyID",
            "summarizeBy": "count"
          },
          {
            "name": "SurveySentDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c70d6dfc-5d27-4698-973e-0966fcb7596d",
            "sourceColumn": "SurveySentDate",
            "summarizeBy": "none"
          },
          {
            "name": "TerriLevel4Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a432ce5a-73d3-4358-a99f-77df0df9afc0",
            "sourceColumn": "TerriLevel4Desc",
            "summarizeBy": "none"
          },
          {
            "name": "TerriLevel5Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe355633-59dc-45d0-831c-c453d7ce2b16",
            "sourceColumn": "TerriLevel5Desc",
            "summarizeBy": "none"
          },
          {
            "name": "TerriLevel6Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11e93cdc-2960-458c-98cc-ea63d66be619",
            "sourceColumn": "TerriLevel6Desc",
            "summarizeBy": "none"
          },
          {
            "name": "TerriLevel7Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "118beba6-3635-4dbe-90d4-8278ebcf0bb2",
            "sourceColumn": "TerriLevel7Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d400f9e4-ed9e-46c1-97eb-677246ff0399",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a8b81fa7-57e1-421f-8699-4345c2a8d885",
        "partitions": [
          {
            "name": "Pyxis Dim-a17a464b-b1ae-4976-908b-ab90afbab3b4",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = PyxisResponseStaging",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Pyxis Field Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "542d4414c7e14b0bab48bad405b37c03"
          }
        ],
        "columns": [
          {
            "name": "Pyxis Field Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "61b777e5-9a4d-44f0-bf14-895dccf92eba",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Pyxis Field Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Pyxis Field Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Pyxis Field Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "1f6d02c9-5133-431f-bd91-8c77cf957a57",
            "sortByColumn": "Pyxis Field Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Pyxis Field Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "d82b8903-2baa-4987-ab1b-6a64aff80231",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "286f43ce-3e93-4ced-a997-6fd2dfb05051",
        "partitions": [
          {
            "name": "Pyxis Field Parameter-57986fa0-c12e-422b-8024-67106c20e7a6",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Department\", NAMEOF('Pyxis Dim'[Department]), 0),",
                "    (\"Designation\", NAMEOF('Pyxis Dim'[Designation]), 1),",
                "    (\"ESVersion\", NAMEOF('Pyxis Dim'[ESVersion (groups)]), 2),",
                "    (\"C2SafeYN\", NAMEOF('Pyxis Dim'[C2Safe]), 3),",
                "    (\"AnesthesiaYN\", NAMEOF('Pyxis Dim'[AnesthesiaYN]), 4),",
                "    (\"AlarisYN\", NAMEOF('Pyxis Dim'[AlarisYN]), 5),",
                "    (\"IDNArea\", NAMEOF('Pyxis Dim'[IDNArea]), 6),",
                "    (\"IDNBucket\", NAMEOF('Pyxis Dim'[IDNBucket]), 7),",
                "    (\"IDNTerritory\", NAMEOF('Pyxis Dim'[IDNTerritory]), 8)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Survey",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Survey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67c8f4ca-55db-4159-9619-343e4236d3e2",
            "sourceColumn": "Survey",
            "summarizeBy": "none"
          },
          {
            "name": "SurveyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isKey": true,
            "lineageTag": "a344cfa8-af36-413b-8efc-a61638fb1729",
            "sourceColumn": "SurveyID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "04f677be-f854-486a-9b8e-cb1cc59f05d5",
        "partitions": [
          {
            "name": "Survey-d4bf491e-e168-4874-8b8d-7deddfc5350f",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUfILCFYIqKzILFaK1YlWMoKKOOYkFoGEYgE=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SurveyID = _t, Survey = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"SurveyID\", Int64.Type}, {\"Survey\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "VOC Follow Up",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Follow-Up Created Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f57bb4cf-626b-4463-abf5-9d35d93e5a4b",
            "sourceColumn": "Follow-Up Created Date",
            "summarizeBy": "none"
          },
          {
            "name": "caseagedaysbucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "849db28a-2d32-45ee-955b-32ffc42c3c8c",
            "sourceColumn": "caseagedaysbucket",
            "summarizeBy": "none"
          },
          {
            "name": "caseownername",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "daa54191-12a3-4a76-be0c-5e7f81ff8f68",
            "sourceColumn": "caseownername",
            "summarizeBy": "none"
          },
          {
            "name": "createddate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f2c0b21-0d33-4606-98ae-f65b139545a2",
            "sourceColumn": "createddate",
            "summarizeBy": "none"
          },
          {
            "name": "description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ff147e6-3fb3-4c5f-a4c0-948bbdb3295d",
            "sourceColumn": "description",
            "summarizeBy": "none"
          },
          {
            "name": "reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f48bfca-9f54-4b90-b56b-18c3de3adeb8",
            "sourceColumn": "reason",
            "summarizeBy": "none"
          },
          {
            "name": "resolution",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fa07431-691d-42a6-953f-9d479908756a",
            "sourceColumn": "resolution",
            "summarizeBy": "none"
          },
          {
            "name": "responseid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "424286be-cc0b-4297-a437-48defaeaafd6",
            "sourceColumn": "responseid",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "432d2f63-18de-475e-9047-a22d811864e4",
            "sourceColumn": "status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3a2d78e1-3d8c-4a53-b17e-6da7a4ce0cc8",
        "partitions": [
          {
            "name": "VOC Follow Up-3e1516b6-35e7-495c-8eb8-8122394732e1",
            "mode": "import",
            "queryGroup": "Model\\Dim",
            "source": {
              "expression": [
                "let",
                "  Source = Dataflows, ",
                "  #\"348982cf-2506-4353-8e3a-d6a5a176bd43\" = Source",
                "    {[dataflowId = \"348982cf-2506-4353-8e3a-d6a5a176bd43\"]}",
                "    [Data], ",
                "  RV_mms_canonical_bdx_voc_follow_up_ = #\"348982cf-2506-4353-8e3a-d6a5a176bd43\"",
                "    {[entity = \"RV_mms_canonical_bdx_voc_follow_up\", version = \"\"]}",
                "    [Data],",
                "  #\"Removed Other Columns\" = Table.SelectColumns(",
                "    RV_mms_canonical_bdx_voc_follow_up_, ",
                "    {",
                "      \"caseownername\", ",
                "      \"status\", ",
                "      \"createddate\", ",
                "      \"caseagedaysbucket\", ",
                "      \"reason\", ",
                "      \"resolution\", ",
                "      \"description\", ",
                "      \"responseid\"",
                "    }",
                "  ), ",
                "  #\"Added Custom\" = Table.AddColumn(",
                "    #\"Removed Other Columns\", ",
                "    \"Follow-Up Created Date\", ",
                "    each Date.FromText(Text.Range([createddate], 0, 10))",
                "  ), ",
                "  #\"Changed Type\" = Table.TransformColumnTypes(",
                "    #\"Added Custom\", ",
                "    {{\"Follow-Up Created Date\", type date}}",
                "  ), ",
                "  #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each [#\"Follow-Up Created Date\"] > #date(2021, 8, 15)), ",
                "  #\"Replaced Value\" = Table.ReplaceValue(",
                "    #\"Filtered Rows\", ",
                "    \"\", ",
                "    \"Blank\", ",
                "    Replacer.ReplaceValue, ",
                "    {\"reason\"}",
                "  ),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Replaced Value\", {\"responseid\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}